# Generated by Django 6.0.7 on 2026-07-28 22:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empresa', models.CharField(max_length=150)),
                ('contacto_nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('objetivo', models.TextField(blank=True)),
                ('presupuesto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado', models.CharField(choices=[('PLANIFICACION', 'En Planificación'), ('ACTIVA', 'Activa'), ('FINALIZADA', 'Finalizada'), ('PAUSADA', 'Pausada')], default='PLANIFICACION', max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campanas', to='agencia.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Creativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('DISEÑO', 'Diseño Gráfico / UI'), ('REDACTION', 'Redacción / Copywriting'), ('VIDEO', 'Edición de Video / Animación'), ('MARKETING', 'Estratega Digital')], default='DISEÑO', max_length=20)),
                ('capacidad_maxima', models.PositiveIntegerField(default=5, help_text='Máximo de tareas/entregables simultáneos')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_creativo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En Proceso'), ('REVISION', 'En Revisión'), ('COMPLETADO', 'Completado')], default='NUEVO', max_length=20)),
                ('fecha_limite', models.DateField()),
                ('campana', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proyectos', to='agencia.campana')),
            ],
        ),
        migrations.CreateModel(
            name='Entregable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('especificaciones', models.TextField(blank=True, help_text='Formato, dimensiones, paleta de colores, etc.')),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='entregables/')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('EN_REVISION', 'En Revisión del Cliente'), ('CORRECCION', 'Requiere Ajustes'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20)),
                ('fecha_entrega', models.DateField()),
                ('creativo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to='agencia.creativo')),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregables', to='agencia.proyecto')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado_por', models.CharField(help_text='Nombre del cliente o director', max_length=100)),
                ('resultado', models.CharField(choices=[('APROBADO', 'Aprobar Entregable'), ('CAMBIOS', 'Solicitar Cambios'), ('RECHAZADO', 'Rechazado Totalmente')], max_length=20)),
                ('comentarios', models.TextField()),
                ('fecha_revision', models.DateTimeField(auto_now_add=True)),
                ('entregable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='agencia.entregable')),
            ],
        ),
    ]
