# Generated by Django 6.0.7 on 2026-07-29 03:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entregable',
            name='creativo',
        ),
        migrations.RemoveField(
            model_name='revision',
            name='entregable',
        ),
        migrations.RemoveField(
            model_name='campana',
            name='estado',
        ),
        migrations.RemoveField(
            model_name='campana',
            name='objetivo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='fecha_registro',
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='archivo_adjunto',
        ),
        migrations.RemoveField(
            model_name='entregable',
            name='especificaciones',
        ),
        migrations.AddField(
            model_name='cliente',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='entregable',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='entregable',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='entregable',
            name='horas_reales',
            field=models.DecimalField(decimal_places=2, default=5.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='entregable',
            name='horas_revision',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='entregable',
            name='rol_responsable',
            field=models.CharField(choices=[('DISEÑADOR', 'Diseñador'), ('COPYWRITER', 'Copywriter')], default='DISEÑADOR', max_length=20),
        ),
        migrations.AlterField(
            model_name='campana',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campana',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='campana',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROCESO', 'En Proceso'), ('CORRECCION', 'Corrección'), ('APROBADO', 'Aprobado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='estado',
            field=models.CharField(choices=[('NUEVO', 'Nuevo'), ('EN_PROCESO', 'En Proceso'), ('REVISION', 'En Revisión'), ('FINALIZADO', 'Finalizado')], default='NUEVO', max_length=20),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='titulo',
            field=models.CharField(max_length=150),
        ),
        migrations.DeleteModel(
            name='Creativo',
        ),
        migrations.DeleteModel(
            name='Revision',
        ),
    ]
