# Generated by Django 6.0.4 on 2026-08-05 12:01

import agencia.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agencia', '0003_cliente_usuario_revision'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='revision',
            old_name='comentario',
            new_name='comentarios',
        ),
        migrations.RenameField(
            model_name='revision',
            old_name='fecha',
            new_name='fecha_revision',
        ),
        migrations.AddField(
            model_name='campana',
            name='estado',
            field=models.CharField(choices=[('PLANIFICACION', 'Planificación'), ('EN_PROGRESO', 'En Progreso'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PLANIFICACION', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='estado',
            field=models.CharField(choices=[('ACTIVO', 'Activo'), ('INACTIVO', 'Inactivo')], default='ACTIVO', max_length=20),
        ),
        migrations.AddField(
            model_name='cliente',
            name='logotipo',
            field=models.ImageField(blank=True, null=True, upload_to='logos/'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='ruc',
            field=models.CharField(blank=True, max_length=13, null=True, unique=True, verbose_name='RUC / Tax ID'),
        ),
        migrations.AddField(
            model_name='entregable',
            name='archivo',
            field=models.FileField(blank=True, null=True, upload_to='entregables/', validators=[agencia.models.validar_peso_archivo]),
        ),
        migrations.AddField(
            model_name='entregable',
            name='fecha_limite',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='entregable',
            name='version',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='horas_estimadas',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='horas_reales',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='prioridad',
            field=models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta'), ('URGENTE', 'Urgente')], default='MEDIA', max_length=20),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='tipo',
            field=models.CharField(choices=[('DISEÑO', 'Diseño'), ('VIDEO', 'Video'), ('BRANDING', 'Branding'), ('WEB', 'Web')], default='DISEÑO', max_length=20),
        ),
        migrations.AddField(
            model_name='revision',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='revision',
            name='archivo_anotaciones',
            field=models.FileField(blank=True, null=True, upload_to='revisiones/', validators=[agencia.models.validar_peso_archivo]),
        ),
        migrations.AddField(
            model_name='revision',
            name='revisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='campana',
            name='presupuesto',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='contacto_nombre',
            field=models.CharField(max_length=100, verbose_name='Contacto Principal'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='presupuesto_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='asignado_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables_legacy', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='estado',
            field=models.CharField(choices=[('POR_INICIAR', 'Por Iniciar'), ('EN_PROCESO', 'En Proceso'), ('EN_REVISION', 'En Revisión'), ('APROBADO', 'Aprobado'), ('RECHAZADO', 'Rechazado')], default='POR_INICIAR', max_length=20),
        ),
        migrations.AlterField(
            model_name='entregable',
            name='rol_responsable',
            field=models.CharField(choices=[('DISEÑADOR_GRAFICO', 'Diseñador Gráfico'), ('COPYWRITER', 'Copywriter'), ('EDITOR_VIDEO', 'Editor Video'), ('DIRECTOR_ARTE', 'Director de Arte')], default='DISEÑADOR_GRAFICO', max_length=30),
        ),
        migrations.AlterField(
            model_name='revision',
            name='realizado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revisiones_realizadas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Creativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('DISEÑADOR_GRAFICO', 'Diseñador Gráfico'), ('COPYWRITER', 'Copywriter'), ('EDITOR_VIDEO', 'Editor Video'), ('DIRECTOR_ARTE', 'Director de Arte')], default='DISEÑADOR_GRAFICO', max_length=30)),
                ('tarifa_hora', models.DecimalField(decimal_places=2, default=25.0, max_digits=8)),
                ('foto_perfil', models.ImageField(blank=True, null=True, upload_to='perfiles/')),
                ('estado', models.CharField(choices=[('DISPONIBLE', 'Disponible'), ('OCUPADO', 'Ocupado')], default='DISPONIBLE', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_creativo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='entregable',
            name='creativo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregables', to='agencia.creativo'),
        ),
    ]
